[package]
name          = "grug-cli"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[[bin]]
name = "grug"
path = "src/main.rs"

[dependencies]
anyhow             = { workspace = true }
bip32              = { workspace = true }
clap               = { workspace = true, features = ["derive", "wrap_help"] }
colored            = { workspace = true }
colored_json       = { workspace = true }
dialoguer          = { workspace = true }
grug-app           = { path = "../crates/app", features = ["abci", "tracing"] }
grug-client        = { path = "../crates/client" }
grug-db-disk       = { path = "../crates/db/disk" }
grug-jmt           = { path = "../crates/jellyfish-merkle" }
grug-types         = { path = "../crates/types" }
grug-vm-wasm       = { path = "../crates/vm/wasm" }
hex                = { workspace = true }
home               = { workspace = true }
rand               = { workspace = true }
serde              = { workspace = true }
tendermint-rpc     = { workspace = true, features = ["http-client"] }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
