[workspace]
resolver = "2"
members  = [
  "bin",
  "contracts/account",
  "contracts/bank",
  "contracts/ibc/clients/tendermint",
  "contracts/tests/*",
  "crates/app",
  "crates/crypto",
  "crates/db/disk",
  "crates/db/memory",
  "crates/jellyfish-merkle",
  "crates/macros",
  "crates/std",
  "crates/storage",
  "crates/testing",
  "crates/types",
  "crates/vm/rust",
  "crates/vm/wasm",
  "crates/wasm",
  "sdk/rust",
]

[workspace.package]
version       = "0.0.0"
authors       = ["Left Curve Software Ltd. (https://leftcurve.software/)"]
edition       = "2021"
rust-version  = "1.73"
documentation = "https://leftcurve.software/grug"
repository    = "https://github.com/left-curve/grug"
license       = "TBD"
keywords      = ["blockchain", "wasm"]
categories    = ["cryptography::cryptocurrencies"]

[workspace.dependencies]
aes-gcm            = "0.10"
anyhow             = "1"
bip32              = "0.5"
blake2             = "0.10"
blake3             = "1"
borsh              = "1"
clap               = "4"
clru               = "0.6"
colored            = "2"
colored_json       = "4"
data-encoding      = "2"
dialoguer          = "0.11"
digest             = "0.10"
dyn-clone          = "1"
ed25519-dalek      = "2"
elsa               = "1"
forward_ref        = "1"
hex                = "0.4"
hex-literal        = "0.4"
home               = "0.5"
k256               = "0.13"
p256               = "0.13"
pbkdf2             = "0.12"
proc-macro2        = "1"
proptest           = "1"
prost              = "0.12"
quote              = "1"
rand               = "0.8"
serde              = "1"
serde_json         = "1"
serde_with         = "3"
sha2               = "0.10"
sha3               = "0.10"
signature          = "2"
syn                = "1"
tempfile           = "3"
tendermint         = "0.34"
tendermint-abci    = "0.34"
tendermint-proto   = "0.34"
tendermint-rpc     = "0.34"
test-case          = "3"
thiserror          = "1"
tokio              = "1"
tracing            = "0.1"
tracing-subscriber = "0.3"
wasmer             = "4"
wasmer-middlewares = "4"

# Our fork of rust-rocksdb is based on the `v0.11.0` release. It adds borsh
# serialization and implements `From`/`TryFrom` traits for `BUint` types.
#
# See the `v0.11.0-grug` branch. comparison:
# https://github.com/isaacholt100/bnum/compare/v0.11.0...left-curve:bnum:v0.11.0-grug
[workspace.dependencies.bnum]
git = "https://github.com/left-curve/bnum"
rev = "91dfe8a"

# Our fork of rust-rocksdb is based on the `v0.21.0` release. It adds partial
# support for the user-defined timestamp feature:
# https://github.com/facebook/rocksdb/wiki/User-defined-Timestamp
#
# See the `v0.21.0-grug` branch. comparison:
# https://github.com/rust-rocksdb/rust-rocksdb/compare/v0.21.0...left-curve:rust-rocksdb:v0.21.0-grug
[workspace.dependencies.rocksdb]
git = "https://github.com/left-curve/rust-rocksdb"
rev = "9015972"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
