[package]
name          = "grug-db-disk"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
grug-app   = { workspace = true }
grug-jmt   = { workspace = true, features = ["ics23"] }
grug-types = { workspace = true }
ics23      = { workspace = true }
rocksdb    = { workspace = true }
tempfile   = { workspace = true }
thiserror  = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
proptest    = { workspace = true }
