[package]
name          = "grug-vm-wasm"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[features]
# Implement `grug_testing::TestVm` trait for `WasmVm`, so that it can be used in
# the test suite.
testing = ["dep:grug-testing"]

[dependencies]
clru               = { workspace = true }
data-encoding      = { workspace = true }
grug-app           = { path = "../../app" }
grug-crypto        = { path = "../../crypto" }
grug-testing       = { path = "../../testing", optional = true }
grug-types         = { path = "../../types" }
serde              = { workspace = true }
thiserror          = { workspace = true }
tracing            = { workspace = true }
wasmer             = { workspace = true, features = ["singlepass"] }
wasmer-middlewares = { workspace = true }

[dev-dependencies]
anyhow        = { workspace = true }
criterion     = { workspace = true }
ed25519-dalek = { workspace = true, features = ["batch", "digest"] }
grug-app      = { path = "../../app", features = ["tracing"] }
grug-bank     = { path = "../../../contracts/bank", features = ["library"] }
grug-crypto   = { path = "../../crypto" }
grug-math     = { path = "../../math" }
grug-tester   = { path = "../../../contracts/tester", features = ["library"] }
grug-testing  = { path = "../../testing" }
grug-vm-wasm  = { path = ".", features = ["testing"] }
k256          = { workspace = true }
p256          = { workspace = true }
rand          = { workspace = true }
test-case     = { workspace = true }

[[bench]]
name = "benchmarks"
harness = false
