[package]
name          = "grug-vm-rust"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
elsa        = { workspace = true }
grug-app    = { path = "../../app" }
grug-crypto = { path = "../../crypto" }
grug-types  = { path = "../../types" }
thiserror   = { workspace = true }

[dev-dependencies]
anyhow       = { workspace = true }
grug-testing = { path = "../../testing" }
serde        = { workspace = true }
test-case    = { workspace = true }
