[package]
name          = "grug-tester-benchmarker"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake3 = { workspace = true }
digest = { version = "0.10" }
grug   = { path = "../../../crates/std" }
k256   = { version = "0.13", default-features = false, features = ["ecdsa"] }
sha2   = { workspace = true }

