[package]
name          = "dango-genesis"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
anyhow      = { workspace = true }
dango-types = { workspace = true }
grug        = { workspace = true }
serde       = { workspace = true }

[dev-dependencies]
bip32       = { workspace = true }
hex         = { workspace = true }
hex-literal = { workspace = true }
home        = { workspace = true }
rand        = { workspace = true }
