[package]
authors       = { workspace = true }
categories    = { workspace = true }
documentation = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
name          = "dango-upgrade"
repository    = { workspace = true }
rust-version  = { workspace = true }

[dependencies]
anyhow                = { workspace = true }
dango-account-factory = { workspace = true }
dango-app             = { workspace = true }
dango-bank            = { workspace = true }
dango-math            = { workspace = true }
dango-primitives      = { workspace = true }
dango-types           = { workspace = true }
tracing               = { workspace = true }
