[package]
name          = "grug-tester-infinite-loop"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
grug = { path = "../../../crates/std" }
